defmodule Phantom.Biometrics.Export do
  @moduledoc """
  One subject's images as a ZIP, for download: faces, fingerprints, palms and
  the tenprint card as PNG, ground truth per print as JSON, a `subject.json`
  manifest and a README saying the data is synthetic.

      PH-5167-ED5B/
        README.txt
        subject.json
        face/mugshot_frontal_F.png
        fingerprints/rolled/fgp02_R_index.png
        fingerprints/rolled/fgp02_R_index_c2.png
        fingerprints/slaps/fgp13_Right_four.png
        palms/plp22_R_writers_palm.png
        card/tenprint_card.png
        ground_truth/fgp02_R_index.json

  `new/2` plans the download (which files, which are missing), `entries/1`
  lists what goes in the archive and `stream/1` produces it lazily: PNGs are
  stored as they are (they're compressed already) and read from storage as
  the ZIP is sent, so a subject of 100 MB never sits in memory.

  `include` is `"all"`, `"faces"` or `"prints"` (fingerprints, palms and the
  card).
  """

  alias Phantom.Biometrics.{Gallery, Image, Run, Shots, Storage, Subject}

  @includes ~w(all faces prints)
  @ppi 500

  @notice "Synthetic test data. This person does not exist: every image was generated by Phantom. " <>
            "Don't use it as evidence of matching accuracy or enrol it in live systems."

  defstruct [:subject, :run, :include, :code, :folder, :filename, :files, :missing, :exported_at]

  @type t :: %__MODULE__{}

  def includes, do: @includes

  @doc """
  Plans the download of `subject`, with its `:run` and `:images` loaded.
  `files` are the images that are rendered and still stored, in the run's
  shot order; `missing` the shots of the run that aren't, and why.
  """
  def new(%Subject{run: %Run{} = run} = subject, include \\ "all") when include in @includes do
    code = Gallery.code(subject.seed)
    images = Map.new(subject.images, &{&1.shot, &1})
    shots = Enum.filter(run.shots, &included?(&1, include))

    {files, missing} =
      Enum.reduce(shots, {[], []}, fn shot, {files, missing} ->
        case images[shot] do
          %Image{} = image ->
            if stored?(image),
              do: {[image | files], missing},
              else: {files, [missing(shot, image) | missing]}

          nil ->
            {files, [%{shot: shot, reason: "not_rendered"} | missing]}
        end
      end)

    %__MODULE__{
      subject: subject,
      run: run,
      include: include,
      code: code,
      folder: code,
      filename: filename(code, include),
      files: Enum.reverse(files),
      missing: Enum.reverse(missing),
      exported_at: DateTime.utc_now() |> DateTime.truncate(:second)
    }
  end

  defp filename(code, "all"), do: "#{code}_synthetic.zip"
  defp filename(code, include), do: "#{code}_#{include}_synthetic.zip"

  defp included?(_shot, "all"), do: true
  defp included?(shot, "faces"), do: Shots.face?(shot)
  defp included?(shot, "prints"), do: Shots.ridge?(shot)

  defp stored?(image), do: Image.rendered?(image) and Storage.exists?(image.storage_key)

  defp missing(shot, %Image{status: :ok}), do: %{shot: shot, reason: "file_missing"}

  defp missing(shot, %Image{status: status, error: error}),
    do: %{shot: shot, reason: Atom.to_string(status), error: error}

  @doc "Whether every shot of the run is in the download and the subject is done rendering."
  def complete?(%__MODULE__{missing: missing, subject: subject}),
    do: missing == [] and not is_nil(subject.completed_at)

  @doc """
  What goes in the archive, in order, as `{path, source}`: `{:file, image}`
  for images (read from storage) and `{:data, iodata}` for generated files.
  """
  def entries(%__MODULE__{} = export) do
    images = for image <- export.files, do: {path(export, image_path(image)), {:file, image}}

    truths =
      for image <- export.files, ground_truth?(image) do
        {path(export, ground_truth_path(image)),
         {:data, Jason.encode_to_iodata!(image.ground_truth, pretty: true)}}
      end

    [
      {path(export, "README.txt"), {:data, readme(export)}},
      {path(export, "subject.json"),
       {:data, Jason.encode_to_iodata!(manifest(export), pretty: true)}}
    ] ++ images ++ truths
  end

  defp path(export, relative), do: export.folder <> "/" <> relative

  @doc "The archive as a lazy stream of iodata chunks."
  def stream(%__MODULE__{} = export) do
    export
    |> entries()
    |> Enum.map(fn
      {path, {:file, image}} ->
        {:ok, data} = Storage.stream(image.storage_key)
        Zstream.entry(path, data, coder: Zstream.Coder.Stored, mtime: mtime(image.updated_at))

      {path, {:data, data}} ->
        Zstream.entry(path, [data], mtime: export.exported_at)
    end)
    |> Zstream.zip()
  end

  defp mtime(%DateTime{} = time), do: DateTime.truncate(time, :second)
  defp mtime(_time), do: DateTime.utc_now() |> DateTime.truncate(:second)

  @doc """
  The manifest (`subject.json`): who the subject is, how they were
  generated, every file with its SHA-256, and the shots that are missing.
  Captures are counted from 1, as in the file names (`_c2`).
  """
  def manifest(%__MODULE__{subject: subject, run: run} = export) do
    by_id = Map.new(export.files, &{&1.id, &1})

    %{
      synthetic: true,
      notice: @notice,
      code: export.code,
      run: run.name,
      subject: subject.name,
      seed: subject.seed,
      description: subject.description,
      attributes: subject.attributes,
      run_settings: %{
        seed: run.seed,
        traits: run.traits,
        prompt_version: run.prompt_version,
        renderer: run.renderer,
        steps: run.steps,
        captures: run.captures
      },
      include: export.include,
      complete: complete?(export),
      exported_at: export.exported_at,
      files: Enum.map(export.files, &file_entry(&1, by_id)),
      missing: export.missing
    }
  end

  defp file_entry(image, by_id) do
    spec = Shots.spec(image.shot) || %{group: "other", code: nil, modality: image.modality}
    reference = image.reference_id && by_id[image.reference_id]

    %{
      path: image_path(image),
      shot: image.shot,
      label: Shots.label(image.shot),
      modality: image.modality,
      group: spec.group,
      position: spec.code,
      capture: (image.capture || 0) + 1,
      width: image.width,
      height: image.height,
      ppi: if(image.modality == :ridge, do: @ppi),
      seed: image.seed,
      prompt: image.prompt,
      reference: reference && image_path(reference),
      sha256: image.sha256,
      bytes: image.byte_size,
      ground_truth: if(ground_truth?(image), do: ground_truth_path(image))
    }
    |> Map.reject(fn {_key, value} -> is_nil(value) end)
  end

  @doc """
  Where an image goes in the archive: `face/mugshot_frontal_F.png`,
  `fingerprints/rolled/fgp02_R_index_c2.png`, `palms/plp21_R_full_palm.png`.
  """
  def image_path(%Image{} = image),
    do: "#{folder(image.shot)}/#{base_name(image)}.#{extension(image)}"

  defp ground_truth_path(image), do: "ground_truth/#{base_name(image)}.json"

  defp ground_truth?(%Image{modality: :ridge, ground_truth: %{} = truth}), do: truth != %{}
  defp ground_truth?(_image), do: false

  defp folder(shot) do
    case Shots.spec(shot) do
      %{group: "face"} -> "face"
      %{group: "rolled"} -> "fingerprints/rolled"
      %{group: "slaps"} -> "fingerprints/slaps"
      %{group: "palms"} -> "palms"
      %{group: "card"} -> "card"
      _other -> "other"
    end
  end

  @doc "The file name of an image without folder or extension: `fgp02_R_index_c2`."
  def base_name(%Image{shot: shot}) do
    case Shots.spec(shot) do
      %{modality: :face, code: pos} ->
        "#{shot}_#{pos}"

      %{group: group, numeric_code: code, label: label, capture: capture}
      when group in ["rolled", "slaps"] ->
        "fgp#{pad(code)}_#{slug(label)}#{capture_suffix(capture)}"

      %{group: "palms", numeric_code: code, label: label, capture: capture} ->
        "plp#{code}_#{slug(label)}#{capture_suffix(capture)}"

      %{group: "card", capture: capture} ->
        "tenprint_card#{capture_suffix(capture)}"

      nil ->
        slug(shot)
    end
  end

  @doc "The name to save one image under: `PH-5167-ED5B_fgp02_R_index.png`."
  def download_name(%Image{} = image, %Subject{seed: seed}),
    do: "#{Gallery.code(seed)}_#{base_name(image)}.#{extension(image)}"

  defp pad(code), do: code |> Integer.to_string() |> String.pad_leading(2, "0")

  defp capture_suffix(0), do: ""
  defp capture_suffix(capture), do: "_c#{capture + 1}"

  defp slug(text) do
    text
    |> String.replace("'", "")
    |> String.replace(~r/[^A-Za-z0-9]+/, "_")
    |> String.trim("_")
  end

  defp extension(%Image{content_type: "image/jpeg"}), do: "jpg"
  defp extension(_image), do: "png"

  @doc """
  What each download holds, for the download menu: `%{"all" => %{files:,
  bytes:}, "faces" => ..., "prints" => ...}`, counting rendered images (ground
  truth and the manifest add a little).
  """
  def summary(%Subject{images: images}) do
    rendered = Enum.filter(images, &Image.rendered?/1)

    Map.new(@includes, fn include ->
      picked = Enum.filter(rendered, &included?(&1.shot, include))
      {include, %{files: length(picked), bytes: Enum.sum_by(picked, &(&1.byte_size || 0))}}
    end)
  end

  defp readme(export) do
    folders =
      [
        {"face/",
         "Face images (PNG). The pose code ends the name: F frontal, L/R profile, A angled."},
        {"fingerprints/",
         "Rolled prints (FGP 1-10) and slaps (FGP 13-15), 500 ppi, 8-bit grey PNG."},
        {"palms/", "Full and writer's palms (PLP 21-24), 500 ppi, 8-bit grey PNG."},
        {"card/", "The tenprint card, built from the same impressions."},
        {"ground_truth/",
         "Per print: minutiae, cores, deltas, pattern class and verification (JSON)."}
      ]
      |> Enum.filter(fn {folder, _text} -> Enum.any?(export.files, &in_folder?(&1, folder)) end)
      |> Enum.map_join("\n", fn {folder, text} ->
        "  #{String.pad_trailing(folder, 16)}#{text}"
      end)

    partial =
      if complete?(export),
        do: "",
        else:
          "\nPARTIAL: some images of this subject are missing or still rendering; see \"missing\" in subject.json.\n"

    """
    #{export.code} - synthetic biometric test subject

    #{@notice}

    Contents
    #{folders}
      subject.json    Who this is, how they were generated, and every file with its SHA-256.

    Extra captures of the same finger or palm end in _c2, _c3.
    #{partial}
    Run #{export.run.name}, #{export.subject.name}, seed #{export.subject.seed}
    Exported #{DateTime.to_iso8601(export.exported_at)}
    """
  end

  defp in_folder?(image, "ground_truth/"), do: ground_truth?(image)
  defp in_folder?(image, folder), do: String.starts_with?(image_path(image), folder)
end
