defmodule Phantom.Biometrics.NistExport do
  @moduledoc """
  One subject as ANSI/NIST-ITL 1-2011 (Update:2015) transactions in
  Traditional encoding (`.an2`), for loading into an ABIS. See
  `docs/nist-export-plan.md`.

  A transaction is one encounter, so a subject becomes:

    * **enrolment** (`<code>_enrol.an2`): the mugshot set (Type-10) and the
      first capture of every rolled finger, slap (Type-14) and palm
      (Type-15). `content` picks `"prints_faces"`, `"prints"` or `"faces"`.
      The tenprint card is left out: its prints are already there.
    * **search** (`<code>_search_aged.an2`, ...): one transaction per chosen
      face probe (`search`), mated with the enrolment.

  Enrolment alone downloads as the `.an2` file; with searches, as a ZIP of
  the files and a README. `compression` (`"png"` or `"wsq"`) applies to
  prints and palms; faces are always PNG (see `Phantom.Biometrics.NistImages`).

  Every transaction says the data is synthetic: Type-1 DOM `PHANTOM`, ORI,
  DAI and SRC `PHANTOM`, and a Type-2 record in Phantom's layout:

  | Field | Content |
  |---|---|
  | 2.003 | Subject code, `PH-5167-ED5B` |
  | 2.004 | `SYNTHETIC TEST DATA - NOT A REAL PERSON - GENERATED BY PHANTOM` |
  | 2.005 | `ENROL` or `SEARCH` |
  | 2.006 | Run name |
  | 2.007 | Subject name in the run, `subject_001` |
  | 2.008 | Subject seed |
  | 2.009 | The probe shot, for a search: `probe_aged` |
  """

  alias Phantom.Biometrics.{Export, FacePrompts, Gallery, Image, NistImages, Run, Shots, Storage}
  alias Phantom.Biometrics.Subject
  alias Phantom.Nist.{Type1, Type10, Type14, Type15, Type2}

  @contents ~w(prints_faces prints faces)
  @compressions ~w(png wsq)

  @enrol_faces ~w(mugshot_frontal mugshot_left_profile mugshot_right_profile
                  mugshot_three_quarter_left mugshot_three_quarter_right)
  @search_faces ~w(probe_aged probe_appearance probe_rebooking probe_glasses probe_low_res
                   icao_portrait)

  # Degrees from full face, positive as the subject turns to their left.
  @pose_angles %{"mugshot_three_quarter_left" => -45, "mugshot_three_quarter_right" => 45}

  @ppi 500
  @agency "PHANTOM"
  @domain {"PHANTOM", "1"}
  @notice "SYNTHETIC TEST DATA - NOT A REAL PERSON - GENERATED BY PHANTOM"

  # Update:2015 impression types: rolled and plain contact; palms keep the
  # palm codes (11: non-live-scan). FCT 2: scanned ink on paper.
  @rolled 1
  @plain 0
  @palm 11
  @ink 2

  defstruct [
    :subject,
    :run,
    :code,
    :content,
    :compression,
    :search,
    :transactions,
    :missing,
    :exported_at
  ]

  @type t :: %__MODULE__{}

  def contents, do: @contents
  def compressions, do: @compressions
  def search_faces, do: @search_faces

  @doc """
  Plans the export of `subject` (with `:run` and `:images` loaded). `opts`
  are `content`, `compression` and `search` (probe shots), as atoms or
  string keys; unknown values fall back to prints with faces, PNG and no
  searches.

  Returns `{:error, :empty}` when there's nothing to export, and
  `{:error, :wsq_unavailable}` for WSQ without `cwsq` installed.
  """
  def new(%Subject{run: %Run{} = run} = subject, opts \\ %{}) do
    opts = normalize(opts)
    stored = Export.new(subject, "all").files
    code = Gallery.code(subject.seed)
    exported_at = DateTime.utc_now() |> DateTime.truncate(:second)

    enrol = enrol_images(stored, opts.content)
    searches = for shot <- opts.search, image = find(stored, shot), do: {shot, image}

    transactions =
      if(enrol == [], do: [], else: [transaction(code, :enrol, nil, enrol, exported_at)]) ++
        for {shot, image} <- searches,
            do: transaction(code, :search, shot, [image], exported_at)

    export = %__MODULE__{
      subject: subject,
      run: run,
      code: code,
      content: opts.content,
      compression: opts.compression,
      search: Enum.map(searches, &elem(&1, 0)),
      transactions: transactions,
      missing: missing(run, enrol, opts.content),
      exported_at: exported_at
    }

    cond do
      transactions == [] -> {:error, :empty}
      opts.compression == "wsq" and not NistImages.wsq_available?() -> {:error, :wsq_unavailable}
      true -> {:ok, export}
    end
  end

  defp normalize(opts) do
    opts = Map.new(opts, fn {key, value} -> {to_string(key), value} end)

    %{
      content: if(opts["content"] in @contents, do: opts["content"], else: "prints_faces"),
      compression: if(opts["compression"] in @compressions, do: opts["compression"], else: "png"),
      search: opts["search"] |> List.wrap() |> Enum.filter(&(&1 in @search_faces)) |> Enum.uniq()
    }
  end

  defp faces?(content), do: content in ["prints_faces", "faces"]
  defp prints?(content), do: content in ["prints_faces", "prints"]

  defp find(images, shot), do: Enum.find(images, &(&1.shot == shot))

  # Mugshots in pose order, then first-capture prints and palms in the run's order.
  defp enrol_images(stored, content) do
    faces =
      if faces?(content), do: for(shot <- @enrol_faces, i = find(stored, shot), do: i), else: []

    prints = if prints?(content), do: Enum.filter(stored, &enrol_print?/1), else: []
    faces ++ prints
  end

  defp enrol_print?(%Image{shot: shot}) do
    match?(%{modality: :ridge, capture: 0, group: group} when group != "card", Shots.spec(shot))
  end

  @doc """
  What `subject` (with `:run` and `:images`) can export, for the export page:
  `%{enrol: %{content => description}, search: [image]}`, the enrolment for
  each `content` (`"5 faces, 10 rolled fingers"`, or `""` when empty) and the
  probe images that are rendered and stored.
  """
  def choices(%Subject{run: %Run{}} = subject) do
    stored = Export.new(subject, "all").files

    %{
      enrol: Map.new(@contents, &{&1, describe_images(enrol_images(stored, &1))}),
      search: for(shot <- @search_faces, image = find(stored, shot), do: image)
    }
  end

  # Enrolment shots of the run that the subject doesn't have (yet).
  defp missing(run, enrol, content) do
    wanted =
      Enum.filter(run.shots, fn shot ->
        (faces?(content) and shot in @enrol_faces) or
          (prints?(content) and
             match?(%{modality: :ridge, capture: 0, group: g} when g != "card", Shots.spec(shot)))
      end)

    wanted -- Enum.map(enrol, & &1.shot)
  end

  defp transaction(code, kind, probe, images, exported_at) do
    stamp = Calendar.strftime(exported_at, "%Y%m%d%H%M%S")

    {name, tcn} =
      case kind do
        :enrol ->
          {"enrol", "#{code}-ENROL-#{stamp}"}

        :search ->
          {"search_#{short(probe)}", "#{code}-SEARCH-#{String.upcase(short(probe))}-#{stamp}"}
      end

    %{
      kind: kind,
      probe: probe,
      name: name,
      filename: "#{code}_#{name}.an2",
      tcn: tcn,
      images: images
    }
  end

  defp short("probe_" <> name), do: name
  defp short("icao_portrait"), do: "icao"
  defp short(shot), do: shot

  @doc "The download's file name: the enrolment `.an2`, or a ZIP when there are several."
  def filename(%__MODULE__{transactions: [only]}), do: only.filename
  def filename(%__MODULE__{code: code}), do: "#{code}_nist.zip"

  @doc "The download's content type."
  def content_type(%__MODULE__{transactions: [_only]}), do: "application/octet-stream"
  def content_type(%__MODULE__{}), do: "application/zip"

  @doc "The download as a lazy stream of iodata: one `.an2`, or a ZIP of them."
  def stream(%__MODULE__{transactions: [only]} = export), do: transaction_stream(export, only)

  def stream(%__MODULE__{} = export) do
    folder = export.code

    entries =
      Enum.map(export.transactions, fn transaction ->
        Zstream.entry(
          "#{folder}/#{transaction.filename}",
          transaction_stream(export, transaction),
          coder: Zstream.Coder.Stored,
          mtime: export.exported_at
        )
      end)

    [Zstream.entry("#{folder}/README.txt", [readme(export)], mtime: export.exported_at) | entries]
    |> Zstream.zip()
  end

  @doc """
  One transaction's bytes as a lazy stream of records: Type-1 and Type-2
  first, then each image record, read and encoded as it's reached.
  """
  def transaction_stream(%__MODULE__{} = export, transaction) do
    records = records(transaction.images)

    header = [
      Type1.build([{2, 0} | Enum.map(records, &{&1.type, &1.idc})],
        tot: tot(transaction.kind),
        date: DateTime.to_date(export.exported_at),
        dai: @agency,
        ori: @agency,
        tcn: transaction.tcn,
        domain: @domain
      ).bytes,
      type2(export, transaction).bytes
    ]

    Stream.concat(header, Stream.map(records, &encode(&1, export.compression)))
  end

  @doc "Transaction bytes in memory, for tests and tools."
  def transaction_bytes(%__MODULE__{} = export, transaction),
    do: export |> transaction_stream(transaction) |> Enum.to_list() |> IO.iodata_to_binary()

  defp tot(:enrol), do: "ENROL"
  defp tot(:search), do: "SEARCH"

  defp type2(export, transaction) do
    fields =
      [
        {3, export.code},
        {4, @notice},
        {5, tot(transaction.kind)},
        {6, export.run.name},
        {7, export.subject.name},
        {8, Integer.to_string(export.subject.seed)}
      ] ++ if(transaction.probe, do: [{9, transaction.probe}], else: [])

    Type2.build(0, fields)
  end

  @doc """
  The records a transaction's images become, with their IDCs (from 1; the
  Type-2 record is 0): `%{type:, idc:, image:}`.
  """
  def records(images) do
    images
    |> Enum.with_index(1)
    |> Enum.map(fn {image, idc} -> %{type: record_type(image), idc: idc, image: image} end)
  end

  defp record_type(%Image{modality: :face}), do: 10

  defp record_type(%Image{shot: shot}) do
    case Shots.spec(shot) do
      %{group: "palms"} -> 15
      _finger -> 14
    end
  end

  defp encode(%{type: 10, idc: idc, image: image}, _compression) do
    {:ok, face} = NistImages.face(read!(image), image)
    pos = FacePrompts.spec(image.shot).pos

    Type10.build(idc, face,
      src: @agency,
      date: capture_date(image),
      sap: if(String.starts_with?(image.shot, "mugshot_"), do: 20, else: 0),
      pos: pos,
      poa: @pose_angles[image.shot]
    ).bytes
  end

  defp encode(%{type: type, idc: idc, image: image}, compression) do
    {:ok, data} = NistImages.print(read!(image), image, @ppi, compression)
    spec = Shots.spec(image.shot)

    opts = [
      imp: impression(spec),
      fgp: spec.numeric_code,
      src: @agency,
      date: capture_date(image),
      fct: @ink
    ]

    case type do
      14 -> Type14.build(idc, data, opts).bytes
      15 -> Type15.build(idc, data, opts).bytes
    end
  end

  defp impression(%{group: "rolled"}), do: @rolled
  defp impression(%{group: "slaps"}), do: @plain
  defp impression(%{group: "palms"}), do: @palm

  defp read!(image) do
    {:ok, data} = Storage.read(image.storage_key)
    data
  end

  defp capture_date(%Image{inserted_at: %DateTime{} = at}), do: DateTime.to_date(at)
  defp capture_date(_image), do: Date.utc_today()

  @doc "A short description of what's in a transaction: `5 faces, 10 rolled, 3 slaps, 4 palms`."
  def describe(transaction), do: describe_images(transaction.images)

  defp describe_images(images) do
    images
    |> Enum.frequencies_by(&group/1)
    |> then(fn counts ->
      for {group, one, many} <- [
            {"face", "face", "faces"},
            {"rolled", "rolled finger", "rolled fingers"},
            {"slaps", "slap", "slaps"},
            {"palms", "palm", "palms"}
          ],
          n = counts[group],
          do: "#{n} #{if n == 1, do: one, else: many}"
    end)
    |> Enum.join(", ")
  end

  defp group(%Image{shot: shot}), do: Shots.spec(shot).group

  defp readme(export) do
    files =
      Enum.map_join(export.transactions, "\n", fn transaction ->
        "  #{String.pad_trailing(transaction.filename, 34)}#{purpose(transaction)}: #{describe(transaction)}"
      end)

    """
    #{export.code} - synthetic biometric test subject, ANSI/NIST-ITL

    Synthetic test data. This person does not exist: every image was generated by Phantom.
    Don't use it as evidence of matching accuracy or enrol it in live systems.

    Files (ANSI/NIST-ITL 1-2011 Update:2015, Traditional encoding)
    #{files}

    Enrol the first file; the search files are the same person, and should find it.
    Prints and palms are #{String.upcase(export.compression)} at 500 ppi; faces are PNG.
    Every file's Type-2 record (2.004) marks it as synthetic, and 2.003 holds #{export.code}.

    Run #{export.run.name}, #{export.subject.name}, seed #{export.subject.seed}
    Exported #{DateTime.to_iso8601(export.exported_at)}
    """
  end

  defp purpose(%{kind: :enrol}), do: "Enrolment"
  defp purpose(%{kind: :search, probe: probe}), do: "Search with #{Shots.label(probe)}"
end
