"""Synthetic friction-ridge service: fingerprints, slaps, palmprints, tenprint cards.

CPU only, no model weights: patterns are generated procedurally (see ridgegen/).
The Phoenix app (Bilder.Biometrics.FrictionRidge) calls this over HTTP on
localhost:8001, and `mix phx.server` starts it (see Bilder.PythonService).

POST /render with JSON {"kind", "code", "seed", "capture"}:

  kind "finger"  code 1-10 (FGP)   rolled finger, 800 x 750
  kind "slap"    code 13, 14, 15   right four / left four / two thumbs, 1600 x 1500
  kind "palm"    code 21-24 (PLP)  21/23 right/left full palm 2750 x 4000,
                                   22/24 right/left writer's palm 875 x 2500
  kind "card"                      FD-249 style tenprint card, 4000 x 4000

`seed` identifies the synthetic person: every image for the same seed shows the
same fingers and palms. `capture` (0, 1, ...) selects a separate capture of
them, for mated pairs. Returns JSON with the 8-bit grey PNG (base64, 500 ppi,
tagged as synthetic) and metadata: pattern classes, singular points, and
ground-truth minutiae where applicable.

Run with `python server.py` (PORT defaults to 8001).
"""

import base64
import io
import os
import sys
import threading
import time
from typing import Literal

from fastapi import FastAPI, HTTPException
from PIL import Image
from PIL.PngImagePlugin import PngInfo
from pydantic import BaseModel, Field

from ridgegen import card, fingerprints, palm

VERSION = "ridgegen/0.1"
PPI = 500

app = FastAPI(title="Synthetic friction-ridge service")

# Generation is CPU heavy and uses all cores itself (FFTs); running requests one
# at a time keeps memory bounded and results just as fast.
_lock = threading.Lock()


class RenderRequest(BaseModel):
    kind: Literal["finger", "slap", "palm", "card"]
    code: int | None = None
    seed: int = Field(ge=0, lt=2**32)
    capture: int = Field(default=0, ge=0, le=9)
    label: str = Field(default="", max_length=80)


@app.get("/health")
def health():
    return {"status": "ready", "version": VERSION}


@app.post("/render")
def render(request: RenderRequest):
    generate = dispatch(request)
    started = time.monotonic()
    with _lock:
        image, meta = generate()
    height, width = image.shape
    return {
        "image": base64.b64encode(encode_png(image, request)).decode("ascii"),
        "width": width,
        "height": height,
        "ppi": PPI,
        "generator": VERSION,
        "duration_ms": round((time.monotonic() - started) * 1000),
        "meta": meta,
    }


def dispatch(request):
    kind, code, seed, capture = request.kind, request.code, request.seed, request.capture
    if kind == "finger" and code in range(1, 11):
        return lambda: fingerprints.rolled(seed, code, capture)
    if kind == "slap" and code in (13, 14, 15):
        return lambda: fingerprints.slap(seed, code, capture)
    if kind == "palm" and code in (21, 22, 23, 24):
        hand = "right" if code in (21, 22) else "left"
        make = palm.full if code in (21, 23) else palm.writers
        return lambda: make(seed, hand, capture)
    if kind == "card":
        return lambda: card.card(seed, capture, request.label)
    raise HTTPException(status_code=400, detail=f"unsupported kind/code: {kind}/{code}")


def encode_png(image, request):
    info = PngInfo()
    info.add_text("Synthetic", "true")
    info.add_text("Comment", "Synthetic test data generated by Bilder. Not a real person.")
    info.add_text("Generator", VERSION)
    info.add_text("Seed", str(request.seed))
    info.add_text("Kind", request.kind)
    info.add_text("Code", str(request.code))
    info.add_text("Capture", str(request.capture))
    buffer = io.BytesIO()
    Image.fromarray(image, mode="L").save(buffer, format="PNG", dpi=(PPI, PPI), pnginfo=info, optimize=False)
    return buffer.getvalue()


def exit_with_parent():
    """Exit when the Phoenix app that started us goes away.

    Bilder.PythonService starts this server with BILDER_EXIT_WITH_PARENT=1 and a
    pipe on stdin; the pipe closes when the BEAM exits, however abruptly (e.g.
    Ctrl+C twice skips the app's shutdown code). Without this, the server would
    keep running and hold the port, and the next `mix phx.server` couldn't
    start its own copy.
    """
    if os.environ.get("BILDER_EXIT_WITH_PARENT") != "1":
        return

    def watch():
        try:
            while sys.stdin.buffer.read(4096):
                pass
        finally:
            os._exit(0)

    threading.Thread(target=watch, daemon=True).start()


if __name__ == "__main__":
    import uvicorn

    exit_with_parent()

    uvicorn.run(app, host=os.environ.get("HOST", "127.0.0.1"), port=int(os.environ.get("PORT", "8001")))
