defmodule Phantom.Biometrics.NistExportTest do
  use Phantom.DataCase, async: true

  import Phantom.BiometricsFixtures

  alias Phantom.Biometrics
  alias Phantom.Biometrics.{FaceAttributes, FacePrompts, Gallery, NistExport, NistImages, Storage}
  alias Phantom.Nist.{Record, Type1}

  @wsq if NistImages.wsq_available?(),
         do: [],
         else: [skip: "needs NIST's cwsq and an2ktool (python_biometrics/setup.sh)"]

  # One subject with mugshots, probes, rolled and slap prints in two
  # captures, a writer's palm and the card.
  setup do
    name =
      create_run(
        subjects: 1,
        shots: [
          "mugshot_left_profile",
          "mugshot_three_quarter_left",
          "probe_aged",
          "probe_appearance",
          "rolled_02",
          "slaps",
          "palm_22",
          "card"
        ],
        captures: 2
      )

    {:ok, subject} = Biometrics.get_subject(name, "subject_001")
    %{name: name, code: Gallery.code(subject.seed)}
  end

  defp decode(export, transaction) do
    {:ok, records} =
      export |> NistExport.transaction_bytes(transaction) |> Phantom.Nist.File.decode()

    Enum.map(records, fn record -> Map.put(record, :fields, Map.new(record.fields)) end)
  end

  defp shots(transaction), do: Enum.map(transaction.images, & &1.shot)

  test "enrols the mugshots and the first capture of every print, without the card", %{
    name: name,
    code: code
  } do
    {:ok, export} = Biometrics.nist_export(name, "subject_001")

    assert [enrol] = export.transactions
    assert enrol.kind == :enrol
    assert NistExport.filename(export) == "#{code}_enrol.an2"
    assert NistExport.content_type(export) == "application/octet-stream"

    assert shots(enrol) == [
             "mugshot_frontal",
             "mugshot_left_profile",
             "mugshot_three_quarter_left",
             "rolled_02",
             "slap_13",
             "slap_14",
             "slap_15",
             "palm_22"
           ]

    assert NistExport.describe(enrol) == "3 faces, 1 rolled finger, 3 slaps, 1 palm"
    assert export.missing == []
  end

  test "the transaction decodes to Type-1, Type-2 and one record per image, as CNT says", %{
    name: name,
    code: code
  } do
    {:ok, export} = Biometrics.nist_export(name, "subject_001")
    [enrol] = export.transactions
    [type1, type2 | images] = decode(export, enrol)

    assert Enum.map(images, & &1.type) == [10, 10, 10, 14, 14, 14, 14, 15]
    assert Enum.map(images, & &1.fields[2]) == Enum.map(1..8, &Integer.to_string/1)

    assert {:ok, cnt} = Type1.decode_cnt(type1.fields[3])
    assert cnt == [{2, 0} | Enum.map(Enum.with_index(images, 1), fn {r, i} -> {r.type, i} end)]

    assert %{2 => "0502", 4 => "ENROL", 7 => "PHANTOM", 8 => "PHANTOM"} = type1.fields
    assert type1.fields[9] =~ ~r/\A#{code}-ENROL-\d{14}\z/
    assert type1.fields[13] == "PHANTOM" <> Record.us() <> "1"

    assert %{3 => ^code, 4 => "SYNTHETIC TEST DATA - NOT A REAL PERSON - GENERATED BY PHANTOM"} =
             type2.fields

    assert %{5 => "ENROL", 6 => ^name, 7 => "subject_001"} = type2.fields
    refute Map.has_key?(type2.fields, 9)

    # Every image goes in as stored.
    assert Enum.all?(images, &(&1.fields[999] == png()))
  end

  test "faces carry their pose; prints their position, impression type and ink", %{name: name} do
    {:ok, export} = Biometrics.nist_export(name, "subject_001")

    [_type1, _type2, frontal, profile, angled, rolled, slap, _slap14, _slap15, palm] =
      decode(export, hd(export.transactions))

    assert %{3 => "FACE", 8 => "0", 11 => "PNG", 12 => "SRGB", 13 => "20", 20 => "F"} =
             frontal.fields

    refute Map.has_key?(frontal.fields, 21)
    assert %{20 => "L"} = profile.fields
    assert %{20 => "A", 21 => "-45"} = angled.fields

    assert %{3 => "1", 6 => "800", 7 => "750", 9 => "500", 11 => "PNG", 13 => "2", 901 => "2"} =
             rolled.fields

    assert %{3 => "0", 13 => "13", 901 => "2"} = slap.fields
    assert palm.type == 15
    assert %{3 => "11", 13 => "22", 901 => "2"} = palm.fields
  end

  test "prints only or faces only", %{name: name} do
    {:ok, prints} = Biometrics.nist_export(name, "subject_001", %{content: "prints"})
    assert Enum.all?(hd(prints.transactions).images, &(&1.modality == :ridge))

    {:ok, faces} = Biometrics.nist_export(name, "subject_001", %{"content" => "faces"})

    assert shots(hd(faces.transactions)) ==
             ~w(mugshot_frontal mugshot_left_profile mugshot_three_quarter_left)
  end

  test "each chosen probe is a search transaction of its own, in a ZIP with the enrolment", %{
    name: name,
    code: code
  } do
    {:ok, export} =
      Biometrics.nist_export(name, "subject_001", %{
        "search" => ["probe_appearance", "probe_aged", "probe_glasses", "secrets"]
      })

    # probe_glasses wasn't rendered and "secrets" isn't a probe.
    assert export.search == ["probe_appearance", "probe_aged"]
    assert [enrol, appearance, aged] = export.transactions
    assert enrol.kind == :enrol
    assert appearance.probe == "probe_appearance"
    assert %{kind: :search, probe: "probe_aged", filename: filename} = aged
    assert filename == "#{code}_search_aged.an2"
    assert shots(aged) == ["probe_aged"]

    [type1, type2, face] = decode(export, aged)
    assert type1.fields[4] == "SEARCH"
    assert type1.fields[9] =~ "#{code}-SEARCH-AGED-"
    assert %{5 => "SEARCH", 9 => "probe_aged"} = type2.fields
    assert %{13 => "0", 20 => "F"} = face.fields

    assert NistExport.filename(export) == "#{code}_nist.zip"
    assert NistExport.content_type(export) == "application/zip"
    zip = export |> NistExport.stream() |> Enum.to_list() |> IO.iodata_to_binary()
    {:ok, files} = :zip.unzip(zip, [:memory])
    files = Map.new(files, fn {path, data} -> {List.to_string(path), data} end)

    assert Map.keys(files) |> Enum.sort() == [
             "#{code}/#{code}_enrol.an2",
             "#{code}/#{code}_search_aged.an2",
             "#{code}/#{code}_search_appearance.an2",
             "#{code}/README.txt"
           ]

    assert files["#{code}/#{code}_search_aged.an2"] ==
             NistExport.transaction_bytes(export, aged)

    assert files["#{code}/README.txt"] =~ "Search with Aged +15: 1 face"
  end

  test "the uncooperative probe is angled, by the subject's own head turn" do
    run = create_run(subjects: 1, shots: ["probe_uncooperative"])
    {:ok, subject} = Biometrics.get_subject(run, "subject_001")
    attrs = FaceAttributes.from_map(subject.attributes)
    angle = FacePrompts.pose_angle("probe_uncooperative", attrs)
    assert abs(angle) in 20..35

    {:ok, export} =
      Biometrics.nist_export(run, "subject_001", %{"search" => ["probe_uncooperative"]})

    [search] = Enum.filter(export.transactions, &(&1.kind == :search))
    assert search.filename =~ "_search_uncooperative.an2"
    [_type1, _type2, face] = decode(export, search)
    assert %{20 => "A"} = face.fields
    assert face.fields[21] == Integer.to_string(angle)
  end

  test "searches without an enrolment when there's nothing to enrol", %{name: name} do
    run = create_run(subjects: 1, shots: ["probe_aged"])
    assert {:error, :empty} = Biometrics.nist_export(run, "subject_001", %{content: "prints"})

    {:ok, export} =
      Biometrics.nist_export(run, "subject_001", %{content: "prints", search: ["probe_aged"]})

    assert [%{kind: :search}] = export.transactions
    assert {:error, :not_found} = Biometrics.nist_export(name, "subject_999")
  end

  test "lists enrolment shots that aren't stored", %{name: name} do
    {:ok, subject} = Biometrics.get_subject(name, "subject_001")
    palm = Enum.find(subject.images, &(&1.shot == "palm_22"))
    File.rm!(Path.join(Storage.Local.root(), palm.storage_key))

    {:ok, export} = Biometrics.nist_export(name, "subject_001")
    assert export.missing == ["palm_22"]
    refute "palm_22" in shots(hd(export.transactions))
  end

  test "choices: what each enrolment holds, and the probes there are", %{name: name} do
    {:ok, subject} = Biometrics.get_subject(name, "subject_001")
    choices = NistExport.choices(subject)

    assert choices.enrol == %{
             "prints_faces" => "3 faces, 1 rolled finger, 3 slaps, 1 palm",
             "prints" => "1 rolled finger, 3 slaps, 1 palm",
             "faces" => "3 faces"
           }

    assert Enum.map(choices.search, & &1.shot) == ["probe_aged", "probe_appearance"]
  end

  describe "with real images" do
    # Replaces a stored image with a real PNG of `bands` 8-bit bands.
    defp store_real_png(subject, shot, bands) do
      image = Enum.find(subject.images, &(&1.shot == shot))
      pixels = :crypto.strong_rand_bytes(image.width * image.height * bands)

      {:ok, vips} =
        Vix.Vips.Image.new_from_binary(
          pixels,
          image.width,
          image.height,
          bands,
          :VIPS_FORMAT_UCHAR
        )

      {:ok, png} = Vix.Vips.Image.write_to_buffer(vips, ".png")
      {:ok, _} = Storage.put(image.storage_key, png)
      png
    end

    test "flattens faces with an alpha channel to RGB", %{name: name} do
      {:ok, subject} = Biometrics.get_subject(name, "subject_001")
      store_real_png(subject, "mugshot_frontal", 4)

      {:ok, export} = Biometrics.nist_export(name, "subject_001", %{content: "faces"})
      [_type1, _type2, frontal | _] = decode(export, hd(export.transactions))

      assert %{6 => "960", 7 => "1280", 11 => "PNG", 12 => "SRGB"} = frontal.fields
      # IHDR colour type 2: RGB, no alpha.
      assert <<137, 80, 78, 71, _::binary-size(21), 2, _::binary>> = frontal.fields[999]
    end

    @tag @wsq
    test "compresses prints as WSQ" do
      run = create_run(subjects: 1, shots: ["rolled_02"])
      {:ok, subject} = Biometrics.get_subject(run, "subject_001")
      store_real_png(subject, "rolled_02", 1)

      {:ok, export} = Biometrics.nist_export(run, "subject_001", %{compression: "wsq"})
      [_type1, _type2, rolled] = decode(export, hd(export.transactions))

      assert %{11 => "WSQ20", 6 => "800", 7 => "750"} = rolled.fields
      # WSQ starts with its SOI marker.
      assert <<0xFF, 0xA0, _::binary>> = rolled.fields[999]
      assert byte_size(rolled.fields[999]) < 800 * 750 / 5
    end

    @tag @wsq
    test "Unify target: WSQ and JPEG, split thumbs and palms, no 14.901" do
      run =
        create_run(
          subjects: 1,
          shots: ["mugshot_left_profile", "rolled_02", "slaps", "palms"]
        )

      {:ok, subject} = Biometrics.get_subject(run, "subject_001")

      for image <- subject.images do
        store_real_png(subject, image.shot, if(image.modality == :face, do: 4, else: 1))
      end

      {:ok, export} = Biometrics.nist_export(run, "subject_001", %{target: "unify"})
      assert %{target: "unify", compression: "wsq"} = export
      [enrol] = export.transactions
      [type1, type2 | records] = decode(export, enrol)

      # Faces by pose (10.020), prints and palms by position (.013).
      assert Enum.map(records, &{&1.type, &1.fields[if(&1.type == 10, do: 20, else: 13)]}) == [
               {10, "F"},
               {10, "L"},
               {14, "2"},
               {14, "13"},
               {14, "14"},
               {14, "11"},
               {14, "12"},
               {15, "26"},
               {15, "25"},
               {15, "22"},
               {15, "28"},
               {15, "27"},
               {15, "24"}
             ]

      assert {:ok, cnt} = Type1.decode_cnt(type1.fields[3])
      assert cnt == [{2, 0} | Enum.map(Enum.with_index(records, 1), fn {r, i} -> {r.type, i} end)]
      assert %{4 => "ENROL", 7 => "PHANTOM"} = type1.fields
      assert %{5 => "ENROL"} = type2.fields

      [frontal, _profile, rolled, slap, _slap14, thumb | _] = records
      # 960 × 1280, cut to 4:5 from the top.
      assert %{11 => "JPEGB", 12 => "SRGB", 13 => "30", 6 => "960"} = frontal.fields
      assert frontal.fields[7] == "1200"
      assert <<0xFF, 0xD8, _::binary>> = frontal.fields[999]

      assert %{3 => "3", 11 => "WSQ20"} = rolled.fields
      assert %{3 => "2"} = slap.fields
      # A plain thumb is at most 1.0 × 2.0 in.
      assert %{3 => "2", 6 => "500", 7 => "1000"} = thumb.fields
      assert Enum.all?(records, &(not Map.has_key?(&1.fields, 901)))
      assert Enum.all?(Enum.filter(records, &(&1.type == 15)), &(&1.fields[3] == "11"))
    end

    @tag @wsq
    @tag :tmp_dir
    test "NBIS an2ktool reads every record", %{name: name, tmp_dir: tmp_dir} do
      {:ok, export} = Biometrics.nist_export(name, "subject_001", %{search: ["probe_aged"]})

      for transaction <- export.transactions do
        # an2ktool writes each image field to a file in its working directory.
        dir = Path.join(tmp_dir, transaction.name)
        File.mkdir_p!(dir)

        File.write!(
          Path.join(dir, transaction.filename),
          NistExport.transaction_bytes(export, transaction)
        )

        {out, status} =
          System.cmd(NistImages.tool("an2ktool"), ["-print", "all", transaction.filename],
            cd: dir,
            stderr_to_stdout: true
          )

        assert status == 0, out
        refute out =~ "ERROR", out
        assert out =~ "[2.004]=SYNTHETIC TEST DATA"
      end
    end
  end
end
