"""A tenprint card in the style of the FBI FD-249 layout, at 500 ppi (8 x 8 in).

Row 1: rolled right thumb .. right little (FGP 1-5)
Row 2: rolled left thumb .. left little (FGP 6-10)
Row 3: left four-finger slap, left thumb, right thumb, right four-finger slap

The card is a visual composite for people to look at, not an interchange
format: the individual 500 ppi images are the real test data. It is always
labelled as synthetic.
"""

import numpy as np
from PIL import Image, ImageDraw, ImageFont

from . import fingerprints as fp

CARD_SIZE = (4000, 4000)
HEADER_H = 600
ROW1_Y, ROW2_Y, ROW3_Y = 690, 1540, 2390
LABEL_H = 60

FINGER_LABELS = {
    1: "R. THUMB", 2: "R. INDEX", 3: "R. MIDDLE", 4: "R. RING", 5: "R. LITTLE",
    6: "L. THUMB", 7: "L. INDEX", 8: "L. MIDDLE", 9: "L. RING", 10: "L. LITTLE",
}


def card(seed, capture=0, subject_label=""):
    w, h = CARD_SIZE
    canvas = Image.new("L", (w, h), 255)
    draw = ImageDraw.Draw(canvas)
    title = ImageFont.load_default(size=110)
    text = ImageFont.load_default(size=44)
    label = ImageFont.load_default(size=36)

    draw.text((60, 60), "SYNTHETIC TEST DATA - NOT A REAL PERSON", font=title, fill=0)
    draw.text((60, 230), f"Tenprint card (FD-249 style layout) · {subject_label}".strip(" ·"), font=text, fill=0)
    draw.text((60, 300), f"Seed {seed} · capture {capture + 1} · 500 ppi · generated by Bilder ridgegen",
              font=text, fill=60)
    draw.text((60, 370), "Not for use in live or production systems.", font=text, fill=60)

    patterns = {}
    for row_y, fingers in ((ROW1_Y, range(1, 6)), (ROW2_Y, range(6, 11))):
        for i, finger in enumerate(fingers):
            image, meta = fp.rolled(seed, finger, capture)
            patterns[finger] = meta["pattern"]
            x = i * 800
            box(draw, x, row_y, 800, 750 + LABEL_H, f"{finger}. {FINGER_LABELS[finger]}", label)
            canvas.paste(Image.fromarray(image), (x, row_y + LABEL_H))

    left_four, _ = fp.slap(seed, 14, capture)
    thumbs, _ = fp.slap(seed, 15, capture)
    right_four, _ = fp.slap(seed, 13, capture)
    slap_h = 1500
    placements = [
        (0, 1600, left_four, "LEFT FOUR FINGERS TAKEN SIMULTANEOUSLY"),
        (1600, 400, thumbs[:, 248:648], "L. THUMB"),
        (2000, 400, thumbs[:, 952:1352], "R. THUMB"),
        (2400, 1600, right_four, "RIGHT FOUR FINGERS TAKEN SIMULTANEOUSLY"),
    ]
    for x, width, image, caption in placements:
        box(draw, x, ROW3_Y, width, slap_h + LABEL_H, caption, label)
        canvas.paste(Image.fromarray(np.ascontiguousarray(image[: h - ROW3_Y - LABEL_H])), (x, ROW3_Y + LABEL_H))

    return np.asarray(canvas), {"capture": capture, "patterns": patterns}


def box(draw, x, y, w, h, caption, font):
    draw.rectangle([x + 2, y, x + w - 2, y + h - 1], outline=0, width=4)
    draw.line([x, y + LABEL_H, x + w, y + LABEL_H], fill=0, width=3)
    draw.text((x + 16, y + 10), caption, font=font, fill=0)
